version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
    container_name: elasticsearch1
    environment: ['http.host=0.0.0.0', 'transport.host=127.0.0.1', 'xpack.security.enabled=false', 'cluster.name=docker-cluster', 'bootstrap.memory_lock=true', 'ES_JAVA_OPTS=-Xms512m -Xmx512m']
    ports: ['127.0.0.1:9200:9200']
    networks: ['stack']
  
  kibana:
    image: opendatastack/kibana:5.6.2
    container_name: kibana1
    ports: ['127.0.0.1:5601:5601']
    networks: ['stack']
    depends_on: ['elasticsearch']

networks: {stack: {}}